//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public decimal Rating { get; set; }
        public string Text { get; set; }
        public System.DateTime ReviewCreationDate { get; set; }
        public System.DateTime RowUpdateTime { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
